use_frameworks!

platform :ios, '10.0'

target 'BusinessModule1_Example' do
  pod 'BusinessModule1', :path => '../'

  target 'BusinessModule1_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
